# This file is automatically generated by find_and_reserve_gpu.py.
# It sets the region and zone dynamically based on where the GPU was successfully reserved.
zone = "us-central1-a"
region = "us-central1"
reservation_name = "machine-learning-gpu-reservation"
machine_type = "g2-standard-4"
accelerator_type = "nvidia-l4"
