# This file is automatically generated by reserve_gpu_and_setup_infrastructure_location.py.
# It sets the region and zone dynamically based on where the GPU was successfully reserved.
zone = "europe-west4-c"
region = "europe-west4"
reservation_name = "machine-learning-gpu-reservation"
machine_type = "g2-standard-4"
accelerator_type = "nvidia-l4"
